version: '3.8'
services:

  postgres:
    image: postgres:16.0
    restart: unless-stopped
    container_name: movieclub_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - movieclub
    volumes:
      - ./_volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  backend:
    container_name: movieclub_backend
    build: ./api/
    ports: 
      - "6200:6200"
    volumes: 
      - ./api:/usr/src/app
      - ./.git:/usr/app/.git
    networks:
      - movieclub
    depends_on:
      postgres:
        condition: service_healthy
      
networks:
  movieclub:
    driver: bridge

volumes:
  postgres-data:
    